/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeeyo_sagar_jeeyodill_StreamplotJNIWrapper */

#ifndef _Included_com_jeeyo_sagar_jeeyodill_StreamplotJNIWrapper
#define _Included_com_jeeyo_sagar_jeeyodill_StreamplotJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jeeyo_sagar_jeeyodill_StreamplotJNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jeeyo_sagar_jeeyodill_StreamplotJNIWrapper_on_1surface_1created
  (JNIEnv *, jclass);

/*
 * Class:     com_jeeyo_sagar_jeeyodill_StreamplotJNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_jeeyo_sagar_jeeyodill_StreamplotJNIWrapper_on_1surface_1changed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_jeeyo_sagar_jeeyodill_StreamplotJNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jeeyo_sagar_jeeyodill_StreamplotJNIWrapper_on_1draw_1frame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
